mysqldbhost = ENTER_YOUR_OWN_INFORMATION
mysqldbname = ENTER_YOUR_OWN_INFORMATION
mysqldbuser = ENTER_YOUR_OWN_INFORMATION
mysqldbpass = ENTER_YOUR_OWN_INFORMATION
mysqlport = ENTER_YOUR_OWN_INFORMATION

mongodbhost = ENTER_YOUR_OWN_INFORMATION
mongodbname = ENTER_YOUR_OWN_INFORMATION

neo4jhost = ENTER_YOUR_OWN_INFORMATION
neo4juser = ENTER_YOUR_OWN_INFORMATION
neo4jpass = ENTER_YOUR_OWN_INFORMATION
neo4jname = ENTER_YOUR_OWN_INFORMATION
